### PR TITLE
19 validations

### PR DESCRIPTION
**Pull request by josh-wilson6289**
Updated our note.js file to have validations on the text field.  Must now be between 3 and 255 characters and cannot be null.  We can also update this object to be text instead of a string if we want more than 255 characters in the future.

### CODE REVIEW

**Review by tylerdrewwork — APPROVED** [review]
looks good! are we going to use Handlebars? We'll need to update the routes when we implement HB if that's the case.

**Comment by tylerdrewwork** [comment]
> looks good! are we going to use Handlebars? We'll need to update the routes when we implement HB if that's the case.

also, this looks like it's branched off of issue #2 maybe? There are commits that include these files in both, not just note.js... can you check that there aren't any overwrites if we merge both of these branches?

**Review by JesseJ713 — APPROVED** [review]
Validation looks good!

**Comment by JesseJ713** [comment]
@Sakiskid it does look like it's branched off of #2. It should be fine to merge both branches without overlap, but I agree it's difficult to track specific changes to the file. Something we can discuss more in detail when we're all together

**Pull request merged**
