### PR TITLE
Additional styling and readme touch ups

### PR DESCRIPTION
**Pull request by DesmondAldridge**
Hey all, any NOTES? <-- I'm going to milk that joke for all it's worth before presentations.

Let me know about colors, textures, positions, content and things.

**Tyler:** The exit button (inside the modal) is being problematic and I'm not too sure why. I can go down that rabbit hole for sure, but if you're able to give it a quick fix (since you're more fluent in sass & grib) then feel free to go for it!

### CODE REVIEW

**Review by JesseJ713 — APPROVED** [review]
Everything looks good in terms of functionality. I like the styling as well! I've included the overlap of the background I get on my screen when I open a note.
image

**Comment by tylerdrewwork** [comment]
https://i.gyazo.com/d447cf24a4cefd7d16b9c2ebf62eb780.png

also having an issue where the bottom clips off... Gonna mark this PR for review and hop in here to try to fix these bugs

**Review by tylerdrewwork — CHANGES_REQUESTED** [review]
Jesse's issue, as well as my issue which we both posted in the comments. Gonna request changes and try to fix them this morning

**Comment by tylerdrewwork** [comment]
tried to make some changes to the text size so it fits. I ended up adjusting margins to get everything on the screen. The Title and Instructions now both use view width units to scale, however the instructions are a bit finnicky and I think we'll need a different approach (one that might take longer) to get them readable at any screen size. 

For Jesse's issue, we're going to need to either make the size of that image bigger to fit the modal at any resollution, or get a loopable/tileable image for the paper... which would be a shame, because this image we're using is so pretty

**Comment by DesmondAldridge** [comment]
> Everything looks good in terms of functionality. I like the styling as well! I've included the overlap of the background I get on my screen when I open a note.
> image

Snap, sorry I missed that. Fixed.

**Comment by DesmondAldridge** [comment]
> tried to make some changes to the text size so it fits. I ended up adjusting margins to get everything on the screen. The Title and Instructions now both use view width units to scale, however the instructions are a bit finnicky and I think we'll need a different approach (one that might take longer) to get them readable at any screen size.
> 
> For Jesse's issue, we're going to need to either make the size of that image bigger to fit the modal at any resollution, or get a loopable/tileable image for the paper... which would be a shame, because this image we're using is so pretty


No worries, won't need all that for the photo/texture. That was just a little oversight on the size ration, I fixed it. 

I'll look into fitting everything else for all views. Mobile first, and otherwise.

**Review by josh-wilson6289 — APPROVED** [review]
Great work, looking good!

**Review by josh-wilson6289 — APPROVED** [review]

**Review by tylerdrewwork — APPROVED** [review]
Sorry about the change request! Are you able to merge now?

**Pull request merged**
